### ISSUE TITLE
Authentication against new user api token feature

### ISSUE THREAD

**Issue by rareshornet** [proxmoxer/proxmoxer#10]
Hi there!

Seems proxmox now supports user api tokens instead of using passwords starting with libpve-access-control 6.0-6. The biggest benefit to me is the fact that you can have different permissions for tokens than users but also that when I'm deving in my own environment I don't have to store my password or create different users with different permissions.

Is this something that you are looking into adding as an alternative auth feature? If not would be a lot of work to implement?

Thanks!

**Comment by jhollowe** [comment]
Can you post a link to some information on this? I can't seem to find information on tokens, other than the tokens that are created by the API from your password.

**Comment by compilenix** [comment]
This is the only thing i was able to find on this topic:
https://pve.proxmox.com/wiki/User_Management#pveum_tokens

**Comment by jhollowe** [comment]
you can view, create, and edit tokens, but using a token as authentication is not yet supported.

Create token:  `proxmox.access.users('test_user@pve').token.put()`  (see [here](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/access/users/{userid}/token/{tokenid}) for mor information)

Considering just how different the authentication method is, we will need to at least create a new Authentication class. We might even need to create a new backend for it, I really don't know.
I'm going to hold this out of the current future release and work on it for the next version.

**Comment by jhollowe** [comment]
for future reference:

> To use an API token, set the HTTP header `Authorization` to the displayed value of the form `PVEAPIToken=USER@REALM!TOKENID=UUID` when making API requests, or refer to your API client documentation.

so probably just a new Auth

**Comment by compilenix** [comment]
https://pve.proxmox.com/wiki/Roadmap#Proxmox_VE_6.2

**Comment by jhollowe** [comment]
Resolved by #20
