### ISSUE TITLE
Dot-Notation issue on /nodes/{node}/qemu/{vmid}/firewall/ipset/{name}/{cidr}

### ISSUE THREAD

**Issue by d4fseeker** [proxmoxer/proxmoxer#100]
When trying to access the API-Path /nodes/{node}/qemu/{vmid}/firewall/ipset/{name}/{cidr} in Dot-Notation it seems impossible to execute it as it doesn't have a "verb" before the CIDR-Address in this case.

I would expect the following to work:
`proxmoxer.nodes(node_name).qemu(vm_id).firewall.ipset(ipset_name,cidr_address).delete()`

However Dot-Notation building can be worked-around when using getattr to dynamically create the CIDR part of the API address:
`getattr(proxmoxer.nodes(node_name).qemu(vm_id).firewall.ipset(ipset_name,cidr_address).delete()`

**Comment by jhollowe** [comment]
you can only have one argument (can be an array) inside each parenthesis. Below are ways to do what you are wanting.

* `proxmoxer.nodes(node_name).qemu(vm_id).firewall.ipset(ipset_name)(cidr_address).delete()`
* `proxmoxer.nodes(node_name).qemu(vm_id).firewall.ipset([ipset_name,cidr_address]).delete()`
* `proxmoxer.nodes(node_name).qemu(vm_id).firewall.ipset(ipset_name).delete(cidr_address)`
