### ISSUE TITLE
Getting VNCProxy information out of proxmoxer

### ISSUE THREAD

**Issue by WillNilges** [proxmoxer/proxmoxer#102]
Hello!

I'm wondering if it's possible to hit the `vncproxy` POST endpoint and the `vncwebsocket` GET endpoint via proxmoxer?

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/vncproxy

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/vncwebsocket

If so, can someone give me an example for how you'd do this?

**Comment by WillNilges** [comment]
This worked for the first call...

```
print(proxmox.nodes("my_proxmox_node").qemu(my_id).vncproxy.post())
```

**Comment by WillNilges** [comment]
Getting this error while running this command:
```
vnc_socket = proxmox.nodes("my_proxmox_node").qemu(my_id).vncwebsocket.get()
```

```
Traceback (most recent call last):
  File "/Users/willard.nilges/Code/python-proxmox-vnc/main.py", line 49, in <module>
    vnc_socket = proxmox.nodes("proxmox01-nrh").qemu(search_id).vncwebsocket.get()
  File "/Users/willard.nilges/Code/python-proxmox-vnc/venv/lib/python3.9/site-packages/proxmoxer/core.py", line 143, in get
    return self(args)._request("GET", params=params)
  File "/Users/willard.nilges/Code/python-proxmox-vnc/venv/lib/python3.9/site-packages/proxmoxer/core.py", line 123, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed. - {'vncticket': 'property is missing and it is not optional', 'port': 'property is missing and it is not optional'}
```

Clearly missing a property---how can I add that?

**Comment by WillNilges** [comment]
Theoretically, this works

```
vnc_socket = proxmox.nodes("my_node").qemu(my_id).vncwebsocket().get(port=vnc_port, vncticket=vnc_ticket)
```

If this all works out, I'm opening a documentation PR.

**Comment by jhollowe** [comment]
It seems that you first need to call `nodes/{node}/qemu/{vmid}/vncproxy` to get the port and ticket information to use with `nodes/{node}/qemu/{vmid}/vncwebsocket`

However, I have no idea how proxmoxer (and ultimately requests) will handle the VNC websocket. I really don't see this being useful for programmatic use, but if to wanted to do that, I don't think you would use proxmoxer to handle the VNC traffic. You can use the `vncproxy` endpoint to setup a connection and use other software to manage the VNC connection.

**Comment by WillNilges** [comment]
Thanks for the info!

I spent yesterday poking around the proxmox forums, and yes, it appears that that secondary endpoint should be used as a websocket (`wss://`) connection. It seems like Proxmox has some patches for noVNC that enable it to handle this. I've been trying to get that set up as a standalone thing, but am struggling. I don't suppose you have any recommendations for VNC clients that can handle websockets?

**Comment by jhollowe** [comment]
Well, I think you can use noVNC which Proxmox uses, but I'm not sure if that will work for your needs.

I'm going to close as it seems proxmoxer is working as intended. If you get something working, feel free to open a PR against the [documentation repo](https://github.com/proxmoxer/docs).
