### ISSUE TITLE
proper checksum-algorithm value passing in the request

### ISSUE THREAD

**Issue by NlVlN** [proxmoxer/proxmoxer#104]
Documentation (https://proxmoxer.github.io/docs/1.2/examples/files/#downloading-files-to-pve) says that it is possible to verify the checksum by providing the checksum and the checksum-algorithm like in the example:
`proxmox.nodes("<node_name>").storage("<storage_name>")("download-url").post(url=sourceURL, content="<content_type>", filename="<file_name.extension>", checksum="<hash>", "checksum-algorithm": "<md5 | sha1 | sha224 | sha256 | sha384 | sha512>")`

However running the following example;
`proxmox.nodes("proxmox").storage("local")("download-url").post(url=iso_url, content="iso", filename=image_name, checksum=sha256sum, "checksum-algorithm": "sha256")`
produces "SyntaxError: positional argument follows keyword argument" error near `checksum-algorithm` parameter.

Is there another method to pass the checksum algorithm to the request, for example, through the variable 'params' or 'data'? I've tried quite a few options and none of them work.

**Comment by jhollowe** [comment]
I know I ran into this when I was testing the downloader, but I forget how I got around it. I'm planning on adding a file upload/download tools module to version 2.0, but haven't got around to that yet.

I think you can create a dict of the arguments you want to pass in and then unpack those into the `post` function call.

e.g. (untested code)
```python
download_args = {"URL": iso_url, "content": "iso", "filename": image_name, "checksum": sha256sum, "checksum-algorithm": "sha256"}
proxmox.nodes("proxmox").storage("local")("download-url").post(**download_args)
```

Let me know if that works.

**Comment by jhollowe** [comment]
Did the above suggestion work for you?

**Comment by NlVlN** [comment]
Thanks! Works like a charm.
The only think I had to do was to change the first dict key to lowercase (‘URL’ to ‘url’).
