### ISSUE TITLE
Getting VM name

### ISSUE THREAD

**Issue by MuhammadShifa** [proxmoxer/proxmoxer#106]
Hello!
Hope you're all doing great.
I have created VM's in Python like 101(Detection). where the name of my VM  is 'Detection'. I am not able to get it with python. I have tried with socket, os and platform but I always get like VM-1 or VM-2 etc. But I should have to get it ''Detection".

Please help me if any one can. Thanks in Advance.

**Comment by jhollowe** [comment]
Please see [the documentation](https://proxmoxer.github.io/docs/1.2/basic_usage/#making-api-calls) for examples of printing out all the VMs ID, names, and statuses.
