### ISSUE TITLE
Make default port configurable

### ISSUE THREAD

**Issue by fernwerker** [proxmoxer/proxmoxer#107]
Hi,
I think this value should not be hard-coded but made configurable (e.g. by host:port) value to make use of API behind reverse proxy that offers tcp/443 UI and not tcp/8006

https://github.com/proxmoxer/proxmoxer/blob/7a49519883e8504ba00102285b3efa0861ad53b7/proxmoxer/core.py#L42

Relates to: https://github.com/prometheus-pve/prometheus-pve-exporter/issues/117

**Comment by jhollowe** [comment]
by definition, a default port must be hard-coded so there can be a default.

But you can pass a port into proxmoxer using either the `port` argument or just adding `:<port>` to the hostname.
The port is extracted from the host and only if it is missing is the default port for that service used.

https://github.com/proxmoxer/proxmoxer/blob/23614c8693a845793484bdeb41349baad7c7d796/proxmoxer/backends/https.py#L277
