### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by tstoco** [proxmoxer/proxmoxer#112]
Hi, 

Thanks for the great job with the project.

I am currently using a proxy to reach my proxmox API. However, I could not find it [implemented anywhere.](https://github.com/proxmoxer/proxmoxer/blob/2ce96b730ac33c42ea3c85cf64cf256cde760b22/proxmoxer/core.py#L159) 

Please let me know if there is a way to use a proxy or if it is [actually not implemented](https://github.com/proxmoxer/proxmoxer/blob/2ce96b730ac33c42ea3c85cf64cf256cde760b22/proxmoxer/backends/https.py#L181) as I suspected.

**Comment by jhollowe** [comment]
Just to confirm, you are trying to use a "proxy" and not a "reverse proxy", correct?

Have you checked if setting the `HTTPS_PROXY` environment variable before running works? The [requests docs](https://requests.readthedocs.io/en/latest/user/advanced/#proxies) show that these environment variables are used if not changed by the code. The docs also show how to use basic auth to authenticate with the proxy.

If you get proxmoxer working with a proxy, I would appreciate a PR to [the docs](https://github.com/proxmoxer/docs/tree/main/docs/examples) to add documentation on the process!

**Comment by CypherpunkSamurai** [comment]
Hello Can I work on this issue? I would really like to check if there's a real bug, just in case, and also document it later :)

**Comment by jhollowe** [comment]
feel free to look into it. I don't think we will need any code change, but adding info on the  `HTTPS_PROXY` environment variable to the [documentation](https://github.com/proxmoxer/docs/tree/main/docs/examples) would be great

**Comment by CypherpunkSamurai** [comment]
No problem. I was hoping to contribute for hactoberfest, but sure. I'll add it to the docs :)

**Comment by jhollowe** [comment]
@CypherpunkSamurai are you still wanting to look into this?

@tstoco have you tried setting `HTTPS_PROXY` before using proxmoxer?

**Comment by jhollowe** [comment]
Closing due to no response. Please reopen if there is new information/progress on this.
