### ISSUE TITLE
Dump Memory VMID

### ISSUE THREAD

**Issue by Robullo** [proxmoxer/proxmoxer#114]
Hi, through proxmox I noticed that some features are not available through these API. In particular, "dump-guest-memory" is not available. Will you ever implement it? or can it already be done but recalling it in a different way?
Thank you

**Comment by jhollowe** [comment]
This is covered in [the documentation](https://proxmoxer.github.io/docs/latest/basic_usage/#invalid-names-in-python). The issue is that Python sees the hyphen and immediately wants to do subtraction. Use the "string notation" to use hyphenated API endpoints.
