### ISSUE TITLE
Implicitly remove None values from params

### ISSUE THREAD

**Issue by kristianheljas** [proxmoxer/proxmoxer#119]
When calling proxmoxer API methods with `None` values, it will behave differently when using https backend vs others.

The difference comes from requests library, which will [implicitly remove `None` values from parameters](https://github.com/psf/requests/blob/1e62a3ec18e19f85ddae03b4cbbdf0b4c62834c0/requests/sessions.py#L82-L86).
On other backends the `None` values are implicitly converted to string, and providing them to the pvesh command.

A stupid, but simple example of this would be:
```python
proxmox.storage.get(type=None) # Will fail, unless https backend is used
```

Would you guys accept a PR removing `None` values just as the requests module does?

This issue surfaced from a [ansible.community issue](https://github.com/ansible-collections/community.general/issues/5449#issuecomment-1304649767) about implementing local backend.

**Comment by jhollowe** [comment]
Sure, always willing to look at PRs!

**Comment by kristianheljas** [comment]
Awsome!

Should same treatment applied to data as well?

I also discovered that [tests utilizing `mock_resource` ](https://github.com/kristianheljas/proxmoxer/blob/63dccd40e2320e90b1fe11faa147c0d99c1af8a8/tests/test_core.py#L118-L197) fixture do not actually check for data integrity. It's because `MockSession.request()` will always return [statically defined `{"data": {"key": "value"}}`](https://github.com/proxmoxer/proxmoxer/blob/63dccd40e2320e90b1fe11faa147c0d99c1af8a8/tests/test_core.py#L310).
Should I adjust the behaviour of `MockSession.request()`  as well?

**Comment by jhollowe** [comment]
Yeah, please improve as much as you want. The tests are just basic right now and could use improvement.

**Comment by kristianheljas** [comment]
@jhollowe Awesome, PR is here: https://github.com/proxmoxer/proxmoxer/pull/120

Thanks!
