### ISSUE TITLE
there is not a description (notes) of an lxc in output

### ISSUE THREAD

**Issue by GusevVictor** [proxmoxer/proxmoxer#130]
I try to use proxmoxer and want to get notes (description) of my lxc container but there is no any kind of description line.

Is it possible to get a description of a lxc container?
 
```
from proxmoxer import ProxmoxAPI
proxmox = ProxmoxAPI('xxxx, user='root@pam', password='111', verify_ssl=False)
proxmox.nodes("xxxx").lxc.get()
```

```
[{'disk': 5077401600,
  'netin': 2306518983,
  'maxswap': 536870912,
  'cpus': 2,
  'type': 'lxc',
  'name': 'docker-tst-on-proxmox',
  'maxdisk': 12573614080,
  'mem': 942215168,
  'status': 'running',
  'cpu': 0.0046971179030262,
  'uptime': 357477,
  'swap': 20480,
  'vmid': '889',
  'maxmem': 4294967296,
  'pid': 163393,
  'diskread': 2543951872,
  'diskwrite': 41126649856,
  'netout': 82636172}]
```

Thank a lot for your answer to me

**Comment by jhollowe** [comment]
Whenever I want to find some data, I typically open up the web UI, navigate to the data I want, and look for the data in the network requests (in the Dev Tools).

By doing this, I found the data on the `nodes/NODE/<lxc or qemu>/ID/config` endpoint under the `description` key.

Please let me know if this is not what you were looking for.

**Comment by GusevVictor** [comment]
Yes. That is was I'm looking. Thank a lot for your answer.
