### ISSUE TITLE
Replace dependency openssh_wrapper with something supported and without unclear license?

### ISSUE THREAD

**Issue by johanneskastl** [proxmoxer/proxmoxer#135]
I built a RPM package for proxmoxer for openSUSE Tumbleweed and confirmed it was working.

But to get the tests working, it seems the `openssh_wrapper` module is needed. This one is not maintained any more, 10+ years old and has an unclear license.

https://github.com/NetAngels/openssh-wrapper/issues/17
https://github.com/NetAngels/openssh-wrapper/issues/15

Is there any chance to replace this with something maintained? Or drop the requirement?
Is it needed for all of the tests?

**Comment by jhollowe** [comment]
The openssh_wrapper module is only used by the openssh backend and its associated tests ([test_openssh.py](https://github.com/proxmoxer/proxmoxer/blob/develop/tests/test_openssh.py) and one or two in [test_imports.py](https://github.com/proxmoxer/proxmoxer/blob/develop/tests/test_imports.py)). If you do not want to use the openssh backend and ignore those tests, the module is not needed.

**Comment by johanneskastl** [comment]
> The openssh_wrapper module is only used by the openssh backend and its associated tests ([test_openssh.py](https://github.com/proxmoxer/proxmoxer/blob/develop/tests/test_openssh.py) and one or two in [test_imports.py](https://github.com/proxmoxer/proxmoxer/blob/develop/tests/test_imports.py)). If you do not want to use the openssh backend and ignore those tests, the module is not needed.

Thanks, that seems to work!
