### ISSUE TITLE
Suspend to disk

### ISSUE THREAD

**Issue by atallo** [proxmoxer/proxmoxer#137]
Proxmox doc says how to suspend the disk.

https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/status/suspend

How do you do with proxmoxer? 

I only get a "normal" suspension

`proxmox.nodes(nombre_nodo).qemu(vm_id).status.post('suspend')`

Thanks! Thisis amazing!

**Comment by jhollowe** [comment]
No Problem. If you want, you can add the information to [the proxmoxer docs](https://proxmoxer.github.io/docs) (most likely as [an example](https://github.com/proxmoxer/docs/tree/main/docs/examples)).
