### ISSUE TITLE
incompatible ssh peer in asa_command module in Ansible 2.9

### ISSUE THREAD

**Issue by badjaoX** [proxmoxer/proxmoxer#14]
Hi, 

Need assistance regarding error on ssh. Incompatible ssh peer (no acceptable kex algorithm).

Appreciate your response. Thank you.

Details:
The full traceback is:
Traceback (most recent call last):
  File "/.ansible/tmp/ansible-local-/ansible-tmp-1584690763.67-219997475427451/AnsiballZ_asa_command.py", line 102, in <modul                         e>
    _ansiballz_main()
  File "/.ansible/tmp/ansible-local-/ansible-tmp-1584690763.67-219997475427451/AnsiballZ_asa_command.py", line 94, in _ansiba                         llz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/.ansible/tmp/ansible-local-/ansible-tmp-1584690763.67-219997475427451/AnsiballZ_asa_command.py", line 40, in invoke_                         module
    runpy.run_module(mod_name='ansible.modules.network.asa.asa_command', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansible/modules/network/asa/asa_command.py", line 186, in <mo                         dule>
  File "/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansible/modules/network/asa/asa_command.py", line 156, in mai                         n
  File "/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansible/module_utils/network/asa/asa.py", line 125, in run_co                         mmands
  File "/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: Incompatible ssh peer (no acceptable kex algorithm)

fatal: [ios01]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/.ansible/tmp/ansible-local-/ansible-tmp-1584690763.67-219                         997475427451/AnsiballZ_asa_command.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/.ansible/tmp/ansible-local-/                         ansible-tmp-1584690763.67-219997475427451/AnsiballZ_asa_command.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, A                         NSIBALLZ_PARAMS)\n  File \"/.ansible/tmp/ansible-local-/ansible-tmp-1584690763.67-219997475427451/AnsiballZ_asa_command.py\",                          line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.asa.asa_command', init_globals=None, run_name='__main__',                          alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2                         .7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 7                         2, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansible/modul                         es/network/asa/asa_command.py\", line 186, in <module>\n  File \"/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip/ansi                         ble/modules/network/asa/asa_command.py\", line 156, in main\n  File \"/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_payload.zip                         /ansible/module_utils/network/asa/asa.py\", line 125, in run_commands\n  File \"/tmp/ansible_asa_command_payload_K0V1WV/ansible_asa_command_p                         ayload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Incompatible ssh peer                          (no acceptable kex algorithm)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by morph027** [comment]
Hi! Proxmoxer is using https://github.com/paramiko/paramiko for ssh connections. I guess, the problem is raised in this module.

Which versions of proxmoxer and paramiko are you using?

**Comment by badjaoX** [comment]
Hi,

Thanks fro prompt response.

I am using paramiko version 2.1.1, but not user the issue is on paramiko since the module stated as connection.py.

Can help on how to force to use kexalgorithm?

Kind Regards,

Michael

________________________________

**Comment by morph027** [comment]
Can you show me an example playbook?

**Comment by badjaoX** [comment]
Hi,

Here is the sample play.

For Network CLI
---
- hosts: ASA1
  connection: network_cli
  vars:
    cli:
     host: "{{ inventory_hostname }}"
     username: "{{ username }}"
     password: "{{ password }}"
     authorize: yes

  tasks:
  - name: Dispaly Certificate
    cli_command:
      command: show run | i crypto


For ASA command
---
- hosts: ASA1
  connection: local
  vars:
    cli:
     host: "{{ inventory_hostname }}"
     username: "{{ username }}"
     password: "{{ password }}"
     authorize: yes

  tasks:
  - name: Dispaly Certificate
    asa_command:
      commands: show run | i crypto
      provider: cli


________________________________

**Comment by morph027** [comment]
Hm, i'm confused, this does not look like something related to proxmoxer module, i see `asa_command` only. This repo is for the proxmoxer requirement in [proxmox module](https://docs.ansible.com/ansible/latest/modules/proxmox_module.html) only.
