### ISSUE TITLE
How to create a container?

### ISSUE THREAD

**Issue by tkbstudios** [proxmoxer/proxmoxer#148]
There's nowhere documented on how to create a container.

**Comment by jhollowe** [comment]
you will need to look at the [PVE docs](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc) for all the options, but the basic fomat will be:

```python
container_config = {"ostemplate":"pve_storage_name:name_of_template.tar.zst", "vmid": 1234}
prox.nodes("example-node").lxc.post(data=container_config)
```

**Comment by tkbstudios** [comment]
Thanks!
