### ISSUE TITLE
Not displaying containers using example from docs

### ISSUE THREAD

**Issue by tkbstudios** [proxmoxer/proxmoxer#149]
I have 5 nodes available with all containers in them but get 0 containers/node outputed.
From [Basic Usage](https://proxmoxer.github.io/docs/2.0/basic_usage/):
```py
>>> # get the list of all the nodes available from the connected node
>>> print(proxmox.nodes.get())
[{'type': 'node', 'node': 'example-node', 'ssl_fingerprint': '63:80:22:...:0D:12', 'id': 'node/example-node', 'status': 'unknown'}]
>>> # use the list of nodes to iterate through each and print the containers and their status
>>> for pve_node in proxmox.nodes.get():
...     print("{0}:".format(pve_node['node']))
...     for container in proxmox.nodes(pve_node['node']).lxc.get():
...         print("\t{0}. {1} => {2}".format(container['vmid'], container['name'], container['status']))
... 
example-node:
        100. container-a => running
        101. container-b => running
        105. container-c => running
```

**Comment by jhollowe** [comment]
Can you provide the code you ran?

**Comment by tkbstudios** [comment]
I literally just gave it xD

**Comment by jhollowe** [comment]
okay, so what does `print(proxmox.nodes.get())` show you? Do you have all the needed permissions on the user/token you are authenticating with (I think the `Auditor` role should give you what you need to do a basic listing out of resources)?

**Comment by tkbstudios** [comment]
Edit: I've been writing my own implementation of a proxmox API and it seems fine to me for now, I won't need your library even if it looks good at first glance ;)
I'm making my own so it works exactly how I want it to.
