### ISSUE TITLE
No ability to set advanced container config

### ISSUE THREAD

**Issue by jskii** [proxmoxer/proxmoxer#15]
From the API documentation here: [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/config](url)

There is the ability to setup advanced configuration of an LXC container; I'm hoping to set some entries in the .conf like:
`lxc.mount.entry: /dev/dri/card0 dev/dri/card0 none bind,optional,create=file`]

I don't believe this is currently possible using proxmoxer, and would like to request it's inclusion in a future update. Thanks!

**Comment by morph027** [comment]
It looks like this can't be set through the API, at least i don't see any related entry in PUT.

**Comment by jhollowe** [comment]
At that link looking at the PUT information, It appears the `features` parameter might be what you are looking for. I'm not sure if the API allows setting all the values you want. I would try using this parameter with the raw API if you can (try curl) and if that works check if Proxmoxer allows the same access.

You can also attempt to do what you want through the web interface and use developer tools (usually F12) to see what API calls it is making (in the Networks tab of the devtools).

If you can get the API to do what you want but not Proxmoxer, let us know, but it looks like the API itself might be limited in this aspect.

**Comment by jhollowe** [comment]
@jskii have you had a chance to see if this is something the API can do?

**Comment by jskii** [comment]
Hi, I moved away from using proxmoxer for my project so I won't be tracking this any longer. Thanks for reaching out.

**Comment by compilenix** [comment]
@jskii may i ask to what solution you moved to?
