### ISSUE TITLE
OIDC Login

### ISSUE THREAD

**Issue by addelovein** [proxmoxer/proxmoxer#155]
I have OIDC Authentication in proxmox and would like to utilize this for my external program.

I have sucessfully authenticated and doing that Proxmox returns.

Username:  adde@mydomain@MYREALM
CSRFToken:  XXXXXXXX:ADMX4wSTXXGhqksXtKHa7X+IXXXXXXXXXXXXXXXXXX
Ticket:  PVE:adde@XXXXXX@MYREALM-AD:XXXXXXX::dpQXXXXXXXXXXXXXXXXXXXXX0aEjosVgeFaZiJbe2HXXXXXXXXXXXXXXXXUafyPRJFjpAJI+6mNvXXXXXXXXXXXXXXXXpJygffXqs875XXXXXXXXXXXXXXXX3yzVUg0wGXa7xFMYMz2ggPAt40d1b4Q==

How can I use this to log in with Proxmoxer?

**Comment by jhollowe** [comment]
I think you can pass the ticket as the password and login with the username&pasword options.
