### ISSUE TITLE
Feature Request: SDN API Support

### ISSUE THREAD

**Issue by joffrey92** [proxmoxer/proxmoxer#162]
Hello Proxmoxer maintainers and community,

I'd like to request the addition of a new feature to support the Proxmox Software-Defined Networking (SDN) API. Proxmox provides a rich set of APIs for managing SDN, which can be found in their documentation here:

[Proxmox SDN API Documentation](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/sdn)

## Requested Feature

The ability to manage Proxmox SDN configurations programmatically through the Proxmoxer Python wrapper would  enhance automation capabilities, making it easier to manipulate zones, controllers, and various other SDN features offered by Proxmox.

- List SDN zones
- Create, update, and delete SDN zones
- List SDN controllers and configure them
- Manage DNS settings

...and other SDN-related actions as outlined in the Proxmox API documentation.

## Use Case

Automated configuration of SDN within Proxmox environments would be beneficial for efficient network management and would allow for better integration into orchestrated workflows that rely on software-defined network configuration and management.

For example, this feature would enable scripting the setup of networks through existing CI/CD pipelines or cloud provisioning tools.

## Additional Context

Proxmoxer already provides an excellent wrapper for interacting with various Proxmox APIs, and the SDN endpoints would complement the existing functionality for virtualization and node management.

Thank you for considering this request, and please let me know if you need any further details or possible contributions towards its implementation.

Thank you for your consideration,
Joffrey

**Comment by jhollowe** [comment]
Does proxmoxer not already work with these API endpoints?

You should be able to initialize a ProxmoxAPI object and then (for example) `prox_obj.cluster.sdn.ipams.get()`
