### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by FrancoTampieri** [proxmoxer/proxmoxer#164]
Python 3.12.3
proxmoxer 2.0.1

Even I put in the connection string the verify_ssl=False the error is everytime rased.

Can u take a look?

**Comment by jhollowe** [comment]
Based on the [urllib3 docs](https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings), you can use the following to disable these warnings:

```python
from urllib3 import disable_warnings
from urllib3.exceptions import InsecureRequestWarning
disable_warnings(InsecureRequestWarning)
```

or just


```python
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

This warning comes from (recent versions of) the libraries used for making HTTPS connections and can't be changed within proxmoxer.

**Comment by FrancoTampieri** [comment]
Thank you that's works like a charm!

Did u consider to switch from requests to https? I did the switch in some project and was very nice, and I can use it with asyncio.

Regards

Franco

**Comment by jhollowe** [comment]
What library is that? do you have a link to it?

**Comment by FrancoTampieri** [comment]
Sure, is that library:
https://www.python-httpx.org

Kind regards

**Comment by jhollowe** [comment]
Interesting. Considering all the `requests`-specific code we have in the app and in the test suite, I think we will stick with `requests` for now. But this is a very cool project and if it becomes more broadly supported we may consider switching to it.
