### ISSUE TITLE
How to create a datastore with keep-monthly option?

### ISSUE THREAD

**Issue by Leetcore** [proxmoxer/proxmoxer#167]
How can i add the prune options to a new datastore?

```
proxmoxer.config.datastore.create(name="datastore-name", path="/test")
```

NOT the correct way:
```
proxmoxer.config.datastore.create(name="datastore-name", path="/test", keep-yearly=1)
```

It's not possible to use this variables "keep-monthly", "keep-yearly", etc. Any ideas?

**Comment by jhollowe** [comment]
Please see my comment on https://github.com/proxmoxer/proxmoxer/issues/159#issuecomment-1981198470 for how to do with with dictionary unpacking
