### ISSUE TITLE
Remote console access

### ISSUE THREAD

**Issue by parham-afkar** [proxmoxer/proxmoxer#168]
How can I connect to the console using proxmoxer? I need remote console access.

**Comment by jhollowe** [comment]
If you are needing console access, I would probably just use the webUI. 

If you want to roll your own version of it, if looks like the webUI uses [nodes/{node}/qemu/{vmid}/vncproxy](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/vncproxy) to get the needed info to create the VNC connection.
If you have the qemu agent installed on your VM guest, you can also use [nodes/{node}/qemu/{vmid}/agent/exec](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec) to execute commands within your VM.
And of course you could just make SSH available in your guest and expose that publicly so you can SSH into it from wherever you need.

If you have a more specific usecase, I can try to help, but I think you would probably get more helpful answers from the proxmox forums.
