### ISSUE TITLE
"No 'get' handler defined for 'host/path'" error after upgrading to 2.1.0 when using openssh backend

### ISSUE THREAD

**Issue by matikij** [proxmoxer/proxmoxer#170]
given script

from proxmoxer import ProxmoxAPI
p=ProxmoxAPI('10.10.10.10', user=None, sudo=True, backend='openssh', timeout=30)
print(p.nodes.get())

I get an exception under 2.1.0:

Traceback (most recent call last):
  File ".../repro.py", line 4, in <module>
    print(p.nodes.get())
          ^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/proxmoxer/core.py", line 167, in get
    return self(args)._request("GET", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/proxmoxer/core.py", line 156, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 500 Internal Server Error: b"No 'get' handler defined for '10.10.10.10/nodes'"

The same script works when using 2.0.1

**Comment by jhollowe** [comment]
If you run `pvesh get nodes`, do you get an error?

What version of PVE are you trying to connect to?

**Comment by matikij** [comment]
czw., 22 sie 2024 o 14:59 John Hollowell ***@***.***>
napisał(a):

> If you run pvesh get nodes, do you get an error?
>
No, but also exactly the same code works on 2.0.1

> What version of PVE are you trying to connect to?
>
7.4

**Comment by laugrean** [comment]
Is there any update on this? 
We also face this issue with proxmoxer 2.1.0?

**Comment by tobytes** [comment]
Same issue on 2.1.0, 2.0.1 it works fine.
PVE: 8.2.7

**Comment by cloudcodger** [comment]
I have encountered this same issue and can reproduce it 100% of the time.

Steps.

1. Install Proxmox 8.2.7 (after install, also ran `apt update` and `apt upgrade` as well) on three systems
2. Use Ansible playbook to create a cluster and set misc. Proxmox VE Datacenter configuration items.

This works under `proxmoxer` 2.0.1 but get these 500 errors with the latest version 2.1.0 as mentioned here.

The Ansible modules are in https://github.com/cloudcodger/proxmox_openssh that this has broken. A good starting point would be the module `cloudcodger.proxmox_openssh.proxmox_group`. Also, downloadable in Ansible Galaxy.

**Comment by asdorsey** [comment]
I'm also seeing this error with the `ssh_paramiko` backend.

```
ERROR:    Traceback (most recent call last):
  File "/app/config.py", line 101, in check_config
    nodes = client.nodes.get()
  File "/usr/local/lib/python3.9/dist-packages/proxmoxer/core.py", line 167, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.9/dist-packages/proxmoxer/core.py", line 156, in _request
    raise ResourceException(
proxmoxer.core.ResourceException: 500 Internal Server Error: No 'get' handler defined for 'proxmox.mydomain.net/nodes'
```

**Comment by asdorsey** [comment]
From what I can tell, this is caused by the host component in the API path.  I've replicated the issue on our Proxmox host using `pvesh`.

```
$ sudo pvesh get proxmox.mydomain.net/nodes --output-format json-pretty
No 'get' handler defined for 'proxmox.mydomain.net/nodes'
super.adam.dorsey@proxmox:~$ sudo pvesh get proxmox/nodes --output-format json-pretty
No 'get' handler defined for 'proxmox/nodes'
super.adam.dorsey@proxmox:~$ sudo pvesh get /nodes --output-format json-pretty
[
   {
      "cpu" : 0.113791521755543,
      "disk" : 15575646208,
      "id" : "node/proxmox",
      "level" : "",
      "maxcpu" : 96,
      "maxdisk" : 24425349120,
      "maxmem" : 1621890441216,
      "mem" : 1137960079360,
      "node" : "proxmox",
      "ssl_fingerprint" : "8B:5D:8B:B1:5C:4C:B4:5D:B0:D1:4D:BE:58:20:E7:3C:E9:59:50:23:C5:EB:DF:43:A9:74:74:66:DC:3D:9A:BC",
      "status" : "online",
      "type" : "node",
      "uptime" : 6058575
   }
]
```
