### ISSUE TITLE
restore vm by api

### ISSUE THREAD

**Issue by freehussain** [proxmoxer/proxmoxer#173]
hello,

i need to restore vm by api, i can't find it cam you please help me

**Comment by jhollowe** [comment]
You will want to look at the [nodes/{node}/qemu (POST)](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu) documentation for PVE and the [proxmoxer docs](https://proxmoxer.github.io/docs/latest/). You can also open the Dev Tools in your browser to the network tab and then restore from the web UI for PVE. You can then view the API request the web UI sent and duplicate that in your code.
