### ISSUE TITLE
Apply network changes

### ISSUE THREAD

**Issue by AmpliFire004** [proxmoxer/proxmoxer#175]
Im having issues applying changes to the network setup on my proxmox node. I'm using the api to create a bridge. But it does not apply the changes. And I can't figure out how to do it

**Comment by jhollowe** [comment]
You are probably better off asking in the [Proxmox Forums](https://forum.proxmox.com/) fo questions on how to use the PVE API as folks there will be more knowledgeable on the specifics of the API.

**Comment by AmpliFire004** [comment]
Does proxmoxer not support it? I guess that was my question.

**Comment by jhollowe** [comment]
proxmoxer can do pretty much anything that the PVE API can do. If you are getting a specific error from proxmoxer, we can look into it more. But I have not personally done anything with network changes via the API so I have no idea how to do it. You can also do what you want in the web UI with your browser's DevTools open to the network tab and see what API calls it makes to do the task you want.
