### ISSUE TITLE
Wrong URL with backend local

### ISSUE THREAD

**Issue by dainok** [proxmoxer/proxmoxer#176]
Seems that Proxmoxer is setting a wrong URL using the local backend:

```python
from proxmoxer import ProxmoxAPI
proxmox = ProxmoxAPI(sudo=False, backend="local")
proxmox.nodes.proxmox1.qemu.get()
```

The error is:

```text
proxmoxer.core.ResourceException: 500 Internal Server Error: No 'get' handler defined for 'localhost/nodes/proxmox1/qemu'
```

The affected file is `proxmoxer/backends/local.py`. Target should be `/` and not `localhost`:

```
class Backend(CommandBaseBackend):
    def __init__(self, *args, **kwargs):
        self.session = LocalSession(*args, **kwargs)
        self.target = "/"
```

With this change the URL is correct:

```text
>>> proxmox.nodes.proxmox1.qemu
ProxmoxResource (/nodes/proxmox1/qemu)
```

If anyone can confirm my usage is correct, I can prepare a patch.

Version:

* Proxmox VE: **8.2.2**
* Proxmoxer: **2.1.0**
* Backend: **local**

**Comment by leahoswald** [comment]
I can confirm the error and that the wrong target was introduced last year with this commit https://github.com/proxmoxer/proxmoxer/commit/500a8dd2e338491b12836510efc767805a464d8a so between the 2.0.1 release and the 2.1.0 release.

**Comment by arthurlunkes** [comment]
PLEASE MERGE IT! Proxmoxer doesn't work for local case. This guy solved it.
