### ISSUE TITLE
automated oidc authentication

### ISSUE THREAD

**Issue by camaeel** [proxmoxer/proxmoxer#182]
Would be great to skip need for passing static tokens. 

It is possible to obtain proxmox ticket + csrf token and use them to authentication. Would be great to have such possibility so OIDC can be used to obtain credentials. 

Either proxmoxer could integrate with https://github.com/camaeel/proxmox-oidc-credential-helper or something similar could be implemented in this lib.

**Comment by jhollowe** [comment]
All you should need to do to use a pre-generated ticket is to pass the ticket values as the password. This will refresh the ticket and CSRF token and will handle keeping these values refreshed during prolonged usage.

Can you confirm if passing the ticket as the password works for you?

**Comment by camaeel** [comment]
I can confirm it works. Thanx @jhollowe for the tip!

**Comment by jhollowe** [comment]
If you have some time, adding how to generate the ticket via OIDC and passing it to proxmoxer would be great to add to [the docs](https://github.com/proxmoxer/docs)!

**Comment by camaeel** [comment]
@jhollowe can you assign this ticket to me then?

**Comment by camaeel** [comment]
@jhollowe Just created a MR here: https://github.com/proxmoxer/docs/pull/6
