### ISSUE TITLE
how to use parameters with a dash 

### ISSUE THREAD

**Issue by daymickcorr** [proxmoxer/proxmoxer#192]
how are we supposed to use parameters with a dash ? 

like cmd-opts
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/termproxy
or input-data
https://proxmox.daymickcorr.com:8006/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/agent/exec

**Comment by morph027** [comment]
See https://github.com/proxmoxer/proxmoxer/issues/159#issuecomment-1981198470

**Comment by daymickcorr** [comment]
ct_info = {"vmid": ctid, ... , "ssh-public-keys": ENCODED_KEYS}
lxc_ct = proxmox.nodes(PROXMOX_NODE_NAME).lxc.create(**ct_info)
