### ISSUE TITLE
Include Proxmox Mail Gateway (PMG) Support

### ISSUE THREAD

**Issue by ananiasfilho** [proxmoxer/proxmoxer#28]
Hello, is possible to include a parameter to define if you will use PVE or PMG?

To proxmoxer lib work with proxmox mail gateway i just changed line bellow:
https://github.com/proxmoxer/proxmoxer/blob/develop/proxmoxer/backends/https.py#L83
        return cookiejar_from_dict({"_**PVE**_"AuthCookie: self.pve_auth_ticket})
TO
        return cookiejar_from_dict({"**_PMG_**"AuthCookie: self.pve_auth_ticket})

and call my pmg api using same resources/requests as:

Example: All users statistics - /api2/json/statistics/sender
Reference: https://pmg.proxmox.com/pmg-docs/api-viewer/index.html#/statistics/sender

```
#!/usr/bin/python3
from proxmoxer import ProxmoxAPI
import json
proxmox = ProxmoxAPI('pmg.mydomain.com', user='root@pam',
                     password='my_password', verify_ssl=False)

a = proxmox.statistics.sender.get()
c = json_formatted_str = json.dumps(a, indent=2)
print(c)
```

So we can define host, user,password and service.
Services are: PVE, PMG and in future PBS - Proxmox Backup Server.

**Comment by nemmeviu** [comment]
+1

**Comment by Disapper** [comment]
+1

**Comment by samirbatista** [comment]
+1

**Comment by jhollowe** [comment]
Yeah, this seems like it shouldn't be that hard. I will need to spin up a PMG instance to test, so it might be on the back burner for a bit, but this will get added soon(tm)

**Comment by ananiasfilho** [comment]
Great!
We are running these changes on Productions servers (12 servers) and created Zabbix and Grafana templates. Its running more than 3 weeks on high load servers. Since its follow same arch of pve api, we have not see differences. Also, just deploy PMG container on your PVE and test. If you have any question, i will be available to help you!
Thank you!

**Comment by garbled1** [comment]
It looks like this code is now merged, per the readme, but the package in pypi doesn't have the new code.  Could you do a new release please?  I want to make a package that depends on this.

**Comment by jhollowe** [comment]
I'd like to do some more work with this and close a few other loose ends before releasing a new version.
I'll try to find some time in the next week or so to release a 1.2.0b1 beta release so you can start playing around with it before the full release. This functionality shouldn't change, just some tidying up of the code.

**Comment by jhollowe** [comment]
version 1.2.0b1 is in pypi. Since it is a prerelease, you will have to manually specify that version for pip to grab it instead of the standard release.

**Comment by jhollowe** [comment]
@ananiasfilho (and others) Can you try running the code in #43 and report back if it works as expected?

You can clone [the PR branch](https://github.com/jhollowe/proxmoxer/tree/service-generalize), and in its directory run `pip install .` to use the branch as the installed version of proxmoxer. You can then import proxmoxer as normal and test its functionality with PBS.
