### ISSUE TITLE
PROXMOX API::command agent implementation

### ISSUE THREAD

**Issue by anujitbhu** [proxmoxer/proxmoxer#36]
Hi,

I am new to proxmoxer and now wisht to implement the agent command to get the Network interfaces IP .
On the server , it works fine through the browser . 

https://172.16.15.31:8006/api2/json/nodes/pve31/qemu/116/agent/network-get-interfaces

But if i am applying it thorugh object then the code is giving an error . 

Please suggest .

Rg

Anuj

**Comment by jhollowe** [comment]
Can you show what code you are trying to use?

**Comment by anujitbhu** [comment]
#!/usr/bin/env python
import sys
import requests
import urllib
import json
from datetime import datetime
from proxmoxer import ProxmoxAPI
proxmox = ProxmoxAPI(sys.argv[1], user='root@pam',password='indian@123', verify_ssl=False)
node=["pve1","pve2","pve3","pve4"];
print(node[0]);
#obj=eval("proxmox.nodes."+node[0]+".qemu.");
for node in proxmox.nodes.get():
    for vm in proxmox.nodes(node['node']).qemu.get():
        if vm['status']=='running':
                ista=proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get('network-get-interfaces')
                print(ista)
~

**Comment by maxlxl** [comment]
@anujitbhu Hi, you posted login credentials. Please change them ASAP. Kind regards

**Comment by jhollowe** [comment]
@anujitbhu Can you also show what error you are getting? Is it "No QEMU guest agent configured"?

**Comment by anujitbhu** [comment]
HI,
--------------------------------------------------------------- The Output Below -----------------------------------------------
Traceback (most recent call last):
  File "/etc/ansible/network.py", line 15, in <module>
    ista=proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get('network-get-interfaces')
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 94, in _request
    resp.reason, resp.content))

**Comment by morph027** [comment]
Can you please use code tags for your output and code? ;)

Is the output all you get from your code? For example, i get traceback like this:

```
>>> for node in proxmox.nodes.get(): 
...     for vm in proxmox.nodes(node['node']).qemu.get(): 
...         if vm['status']=='running': 
...             proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get('network-get-interfaces')                                                                                                                                                                                                                              
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/morph/python3/lib/python3.8/site-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/home/morph/python3/lib/python3.8/site-packages/proxmoxer/core.py", line 90, in _request
    raise ResourceException("{0} {1}: {2} - {3}".format(
proxmoxer.core.ResourceException: 500 Internal Server Error: QEMU guest agent is not running - b'{"data":null}'

500 Internal Server Error: QEMU guest agent is not running - b'{"data":null}'
```

**Comment by morph027** [comment]
Example:

```
>>> proxmox.nodes('proxmox2').qemu('101').agent.get()                                                                                                                                                                                                                                                                         
[{'name': 'exec'}, {'name': 'exec-status'}, {'name': 'file-read'}, {'name': 'file-write'}, {'name': 'fsfreeze-freeze'}, {'name': 'fsfreeze-status'}, {'name': 'fsfreeze-thaw'}, {'name': 'fstrim'}, {'name': 'get-fsinfo'}, {'name': 'get-host-name'}, {'name': 'get-memory-block-info'}, {'name': 'get-memory-blocks'}, {'name': 'get-osinfo'}, {'name': 'get-time'}, {'name': 'get-timezone'}, {'name': 'get-users'}, {'name': 'get-vcpus'}, {'name': 'info'}, {'name': 'network-get-interfaces'}, {'name': 'ping'}, {'name': 'set-user-password'}, {'name': 'shutdown'}, {'name': 'suspend-disk'}, {'name': 'suspend-hybrid'}, {'name': 'suspend-ram'}]

>>> proxmox.nodes('proxmox2').qemu('101').agent.get('network-get-interfaces')                                                                                                                                                                                                                                                 
{'result': [{'name': 'Ethernet', 'statistics': {'rx-packets': 346117416, 'rx-bytes': 269971596579, 'rx-dropped': 0, 'tx-errs': 0, 'tx-dropped': 0, 'tx-bytes': 293573296251, 'tx-packets': 363280783, 'rx-errs': 0}, 'ip-addresses': [{'ip-address': '192.168.x.y', 'prefix': 24, 'ip-address-type': 'ipv4'}], 'hardware-address': 'xx:xx:xx:xx:xx:xx'}, {'name': 'Loopback Pseudo-Interface 1', 'ip-addresses': [{'ip-address': '::1', 'prefix': 128, 'ip-address-type': 'ipv6'}, {'prefix': 8, 'ip-address-type': 'ipv4', 'ip-address': '127.0.0.1'}], 'statistics': {'rx-errs': 0, 'tx-dropped': 0, 'tx-bytes': 0, 'tx-packets': 0, 'tx-errs': 0, 'rx-packets': 0, 'rx-bytes': 0, 'rx-dropped': 0}}, {'statistics': {'tx-dropped': 0, 'tx-bytes': 0, 'tx-packets': 0, 'rx-errs': 0, 'rx-bytes': 0, 'rx-packets': 0, 'rx-dropped': 0, 'tx-errs': 0}, 'name': 'isatap.{<uuid-redacted>}', 'hardware-address': '00:00:00:00:00:00'}]}
```

**Comment by jhollowe** [comment]
It looks like this could be a python 2 issue, or it might just be the lack of a qemu guest agent.

**Comment by anujitbhu** [comment]
Hi John,

please find our code below
```
#!/usr/bin/env python
import sys
import requests
import urllib
import json
from datetime import datetime
from proxmoxer import ProxmoxAPI
proxmox = ProxmoxAPI(sys.argv[1], user='xxxxxx',password='yyyyyy', verify_ssl=False)
node=["pve1","pve2","pve3","pve4"];
print(node[0]);
#obj=eval("proxmox.nodes."+node[0]+".qemu.");
for node in proxmox.nodes.get():
    for vm in proxmox.nodes(node['node']).qemu.get():
        if vm['status']=='running':
                ista=proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get()
                print "{0}--{1}==>{2}\n".format(node,vm['name'],ista)

```

this gives no error -->with the output 

> 
> pve4--WHM==>[{u'name': u'exec'}, {u'name': u'exec-status'}, {u'name': u'file-read'}, {u'name': u'file-write'}, {u'name': u'fsfreeze-freeze'}, {u'name': u'fsfreeze-status'}, {u'name': u'fsfreeze-thaw'}, {u'name': u'fstrim'}, {u'name': u'get-fsinfo'}, {u'name': u'get-host-name'}, {u'name': u'get-memory-block-info'}, {u'name': u'get-memory-blocks'}, {u'name': u'get-osinfo'}, {u'name': u'get-time'}, {u'name': u'get-timezone'}, {u'name': u'get-users'}, {u'name': u'get-vcpus'}, {u'name': u'info'}, {u'name': u'network-get-interfaces'}, {u'name': u'ping'}, {u'name': u'set-user-password'}, {u'name': u'shutdown'}, {u'name': u'suspend-disk'}, {u'name': u'suspend-hybrid'}, {u'name': u'suspend-ram'}]
> 
> pve4--cenots==>[{u'name': u'exec'}, {u'name': u'exec-status'}, {u'name': u'file-read'}, {u'name': u'file-write'}, {u'name': u'fsfreeze-freeze'}, {u'name': u'fsfreeze-status'}, {u'name': u'fsfreeze-thaw'}, {u'name': u'fstrim'}, {u'name': u'get-fsinfo'}, {u'name': u'get-host-name'}, {u'name': u'get-memory-block-info'}, {u'name': u'get-memory-blocks'}, {u'name': u'get-osinfo'}, {u'name': u'get-time'}, {u'name': u'get-timezone'}, {u'name': u'get-users'}, {u'name': u'get-vcpus'}, {u'name': u'info'}, {u'name': u'network-get-interfaces'}, {u'name': u'ping'}, {u'name': u'set-user-password'}, {u'name': u'shutdown'}, {u'name': u'suspend-disk'}, {u'name': u'suspend-hybrid'}, {u'name': u'suspend-ram'}]
> 
> pve4--cenots2==>[{u'name': u'exec'}, {u'name': u'exec-status'}, {u'name': u'file-read'}, {u'name': u'file-write'}, {u'name': u'fsfreeze-freeze'}, {u'name': u'fsfreeze-status'}, {u'name': u'fsfreeze-thaw'}, {u'name': u'fstrim'}, {u'name': u'get-fsinfo'}, {u'name': u'get-host-name'}, {u'name': u'get-memory-block-info'}, {u'name': u'get-memory-blocks'}, {u'name': u'get-osinfo'}, {u'name': u'get-time'}, {u'name': u'get-timezone'}, {u'name': u'get-users'}, {u'name': u'get-vcpus'}, {u'name': u'info'}, {u'name': u'network-get-interfaces'}, {u'name': u'ping'}, {u'name': u'set-user-password'}, {u'name': u'shutdown'}, {u'name': u'suspend-disk'}, {u'name': u'suspend-hybrid'}, {u'name': u'suspend-ram'}]
> 
> pve4--RemoteUbuntu16==>[{u'name': u'exec'}, {u'name': u'exec-status'}, {u'name': u'file-read'}, {u'name': u'file-write'}, {u'name': u'fsfreeze-freeze'}, {u'name': u'fsfreeze-status'}, {u'name': u'fsfreeze-thaw'}, {u'name': u'fstrim'}, {u'name': u'get-fsinfo'}, {u'name': u'get-host-name'}, {u'name': u'get-memory-block-info'}, {u'name': u'get-memory-blocks'}, {u'name': u'get-osinfo'}, {u'name': u'get-time'}, {u'name': u'get-timezone'}, {u'name': u'get-users'}, {u'name': u'get-vcpus'}, {u'name': u'info'}, {u'name': u'network-get-interfaces'}, {u'name': u'ping'}, {u'name': u'set-user-password'}, {u'name': u'shutdown'}, {u'name': u'suspend-disk'}, {u'name': u'suspend-hybrid'}, {u'name': u'suspend-ram'}]
> 

But when I inset the parameter in the same command 

 `ista=proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get('network-get-interaces')`

It gives the error 

> Traceback (most recent call last):
>   File "/etc/ansible/network.py", line 15, in <module>
>     ista=proxmox.nodes(node['node']).qemu(vm['vmid']).agent.get('network-get-interfaces')
>   File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 105, in get
>     return self(args)._request("GET", params=params)
>   File "/usr/local/lib/python2.7/dist-packages/proxmoxer/core.py", line 94, in _request
>     resp.reason, resp.content))
> proxmoxer.core.ResourceException: 501 Not Implemented: Method 'GET /nodes/pve1/qemu/221/agent/network-get-interfaces' not implemented - {"data":null}
> 


Where as when i put the same url on browser it gives me a result 

`https://172.16.15.10:8006/api2/json/nodes/pve1/qemu/221/agent/network-get-interfaces
`
`{"data":{"result":[{"ip-addresses":[{"ip-address-type":"ipv4","ip-address":"127.0.0.1","prefix":8},{"ip-address-type":"ipv6","prefix":128,"ip-address":"::1"}],"name":"lo","hardware-address":"00:00:00:00:00:00"},{"name":"ens18","hardware-address":"c2:96:5d:76:75:94"},{"hardware-address":"02:42:3e:47:5a:ec","name":"br-c56cfb43fced","ip-addresses":[{"ip-address-type":"ipv4","ip-address":"172.20.0.1","prefix":16}]},{"name":"docker0","hardware-address":"02:42:8d:43:f0:c1","ip-addresses":[{"ip-address-type":"ipv4","ip-address":"172.17.0.1","prefix":16}]},{"ip-addresses":[{"ip-address-type":"ipv4","ip-address":"172.18.0.1","prefix":16}],"name":"br-f944b1ebaa9b","hardware-address":"02:42:ca:48:66:b4"}]}}
`

Please suggest .

**Comment by morph027** [comment]
Which version of proxmoxer are you using?

Can you try using python3 instead of EOL'd python2?

**Comment by anujitbhu** [comment]
proxmoxer 1.1.1

**Comment by anujitbhu** [comment]
we are using the proxmox default debian image which comes with the default python 2.7.16 version . Thereby we prefer to use the dafault package only

**Comment by anujitbhu** [comment]
We have resolved the issue by using Try Catch as this API throws exception if the data is NULL .
