### ISSUE TITLE
"proxmoxer required for this module", yet proxmoxer is installed on Macos

### ISSUE THREAD

**Issue by bronsgeest** [proxmoxer/proxmoxer#37]
When executing an ansible playbook on Macos Catalina (Apple) I continue to have the fatal error: "fatal: [proxy-test]: FAILED! => {"changed": false, "msg": "proxmoxer required for this module"} 

This is not a proxmoxer issue, but some Apple thing I assume.

pip3 show proxmoxer 1.1.1, Location: /usr/local/lib/python3.8/site-packages
ansible 2.9.13 using python version = 3.8.5
Macos: 10.15.7

Initially poxmoxer was installed in python3.7/site-packages. Removing and reinstalling proxmoxer wiht pip3 fixed that and it is now in python3.8/site-packages. Yet the behaviour remains the same. I can run the same playbook normally when I "ssh -A" into a debian10 VM running on the same Apple laptop. 

What extra debug info can I enable to find the reason for the error? Is someone familiar with the same behaviour on an Apple and was that fixed?

Max

**Comment by jhollowe** [comment]
This seems to be an issue with Ansible, not proxmoxer. Please file a [bug report with Ansible](https://github.com/ansible/ansible/issues/new?template=bug_report.md) so people with knowledge of Ansible can help you with this issue.

**Comment by bronsgeest** [comment]
Thx for your reply, I did not expect ansible could be the problem. I will follow up with them.
