### ISSUE TITLE
How i can get status from one machine ? 

### ISSUE THREAD

**Issue by deadbyhost** [proxmoxer/proxmoxer#40]
hello i want to know how i can get  nodes.lxc.vmid.current.get() but whit a custom machine , whit a function parameter not gettig all vms

**Comment by deadbyhost** [comment]
i did whit whit 

    for node in proxmox.nodes.get():
        for vm in proxmox.nodes(node['node']).lxc.get():
            if vm['vmid'] == vmid :
                print(vm['vmid'] + vm['status'])

**Comment by morph027** [comment]
if you know on which node the container is running: `proxmox.nodes(node_id).lxc(lxc_id).status.get('current')`

**Comment by deadbyhost** [comment]
> 
> 
> if you know on which node the container is running: `proxmox.nodes(node_id).lxc(lxc_id).status.get('current')`

Thanks u so much , works pretty well 👍 , have nice day
