### ISSUE TITLE
PBS Support

### ISSUE THREAD

**Issue by tuxis-ie** [proxmoxer/proxmoxer#42]
Is anyone working on PBS support already?

**Comment by jhollowe** [comment]
Is there official API documentation for PBS? I looked a little while ago and didn't find anything. It *should* be super easy to add support if it follows the same basic API spec for auth and stuff.

**Comment by tuxis-ie** [comment]
No, not yet.

Some testing by me shows that for https-as-a-user, the otp-json part is not supposed to be sent. The authentication-header is called PBS-etc instead of PVE-etc, but I did not manage to get that working (although I'm not sure if I understand the proxmoxer-code enough :))

**Comment by jhollowe** [comment]
As long as it uses some of the same authentication and layout methods (which from looking into the PBS integrations into the other Proxmox services looks likely), it should be incredibly easy to add PBS support. #34 should make it so we can just add "PBS" to `SUPPORTED_SERVICES` and it should just work. We will of course need to do testing to ensure what parts are and are not compatible.

**Comment by jhollowe** [comment]
Just found more info as well confirming API Token support in PBS: https://pbs.proxmox.com/docs/user-management.html#api-tokens

**Comment by jhollowe** [comment]
It looks like there are a few things not working yet ([waiting on a response about API Tokens](https://forum.proxmox.com/threads/api-token-problems.81020/)), but basic HTTPS username/password auth and standard queries seem to be working by adding "PBS" to `SUPPORTED_SERVICES` in `core.py` in the develop branch.

**Comment by jhollowe** [comment]
@tuxis-ie Can you try running the code in #43 and report back if it works as expected?

You can clone [the PR branch](https://github.com/jhollowe/proxmoxer/tree/service-generalize), and in its directory run `pip install .` to use the branch as the installed version of proxmoxer. You can then import proxmoxer as normal and test its functionality with PBS.

**Comment by wmorgue** [comment]
Hi @jhollowe and thank you for the good work 👍🏻

I tested some API calls with `service-generalize` branch. The screenshot below shows which methods work or don't work.

![Screen Shot 2021-05-21 at 14 35 59](https://user-images.githubusercontent.com/24982084/119131441-28cc0800-ba42-11eb-8de2-1b598ffe750f.png)


```python
{'pong': True}
[{'comment': 'Linux PAM standard authentication', 'default': True, 'realm': 'pam'}, {'comment': 'Proxmox Backup authentication server', 'realm': 'pbs'}]
Method's below ⬇ doesn't working with same error: 

Traceback (most recent call last):
  File "/Users/moon/Developer/Work/pbs_api/src/main.py", line 37, in <module>
    print(proxmox.version.get())
  File "/Users/moon/.local/share/virtualenvs/pbs_api-zUSF1Mt6/lib/python3.9/site-packages/proxmoxer/core.py", line 155, in get
    return self(args)._request("GET", params=params)
  File "/Users/moon/.local/share/virtualenvs/pbs_api-zUSF1Mt6/lib/python3.9/site-packages/proxmoxer/core.py", line 123, in _request
    if resp.json().get("errors") != None:
  File "/Users/moon/.local/share/virtualenvs/pbs_api-zUSF1Mt6/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The other methods fall with the same error. Python 3.9.5.


PBS Version API — https://pbs.proxmox.com/docs/api-viewer/index.html#/version

**Comment by jhollowe** [comment]
hrm, using PBS 1.1-1, I get the following:
```
>>> pbs = ProxmoxAPI('1.2.3.4', user='root@pam', password='password', verify_ssl=False, service='pbs')
>>> pbs.version.get()
{'release': '1', 'repoid': '', 'version': '1.1'}
```

Can you confirm that the API is returning JSON for the version endpoint? if you log into PBS in your browser and then go to `https://<your_ip>:8007/api2/json/version`, what is the text that appears?

**Comment by wmorgue** [comment]
@jhollowe damn, i forgot write `service="PBS"` into `ProxmoxAPI` class 😅
Works without errors. Yep, also web JSON works or `127.0.0.1:82/api2/json/version`.

Thank you 👍🏻
