### ISSUE TITLE
I don't know how to read lxc config

### ISSUE THREAD

**Issue by nklamann** [proxmoxer/proxmoxer#47]
Hello all,
 want to extract the existing  configuration of a PVE Node for documentation purposes.

I have no trouble to display some metadata of the lxc. But how do I get the config ?

In pvesh it looks like this: 

` pvesh get  /nodes/xxx/lxc/200/config/
`

In python I do:

    from proxmoxer import ProxmoxAPI

    proxmox = ProxmoxAPI('xxx.de', user=yyy',
                     password='yyyyyy', verify_ssl=False)

    for node in proxmox.nodes.get():
        for lxc in proxmox.nodes(node['node']).lxc.get():
            print (lxc)

the dictionary `lxc` does not contain a 'config' and I did not manage to extract this information in any way i tried.

How shall this be done ?

Thanks for reading !

Norbert

**Comment by jhollowe** [comment]
From looking at the [API documentation](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/config), it looks like you just need to add config to your query. Also, make sure you have the VM.Audit permission for everything.

For example:
```python
from proxmoxer import ProxmoxAPI

proxmox = ProxmoxAPI('xxx.de', user='yyy@realm',
                                       password='yyyyyy', verify_ssl=False)

for node in proxmox.nodes.get():
    for lxc in proxmox.nodes(node['node']).lxc.get():
        config = proxmox.nodes(node['node']).lxc(lxc["vmid"]).config.get()
        print (config)
        print(config["template"])
```

**Comment by nklamann** [comment]
Thanks a lot . That didi it . I was confused after reading in the README:

> As a demonstration of the flexibility of usage of this library, the following lines accomplish the equivalent function:
proxmox.nodes(node['node']).openvz.get()
proxmox.nodes(node['node']).get('openvz')
proxmox.get('nodes/%s/openvz' % node['node'])
proxmox.get('nodes', node['node'], 'openvz')

`proxmox.get('nodes/%s/openvz' % node['node'])` threw me off the rails

Thanks again !
