### ISSUE TITLE
proxmox.get(item) not working?

### ISSUE THREAD

**Issue by edofullin** [proxmoxer/proxmoxer#49]
I get errors with this code:

```
from proxmoxer import ProxmoxAPI

proxmox=ProxmoxAPI('proxmox.myhost.net', user='user@pve', password='secret', verify_ssl=False)

vms = []
containers = []

for node in proxmox.get("nodes"):

            for virtman in proxmox.get(f"nodes/{node}/qemu"):
                vms.append(virtman["vmid"])

            for cont in proxmox.get(f"nodes/{node}/lxc"):
                containers.append(cont["vmid"])

```

The error in question is on the outermost for loop and is

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ProxmoxResource' object is not iterable
```

I'm using Proxmox 6.3-6 and Python 3.9

Using proxmox.nodes.get() insted works correctly, but I would like to use proxmox.get("nodes")

Am I doing something wrong?

**Comment by jhollowe** [comment]
> Using proxmox.nodes.get() insted works correctly, but I would like to use proxmox.get("nodes")

Is there a specific reason you can't use the `proxmox.nodes.get()` format?

What version of proxmoxer are you using?

**Comment by edofullin** [comment]
The reason was that unit testing was going to be easier, but eventually I managed to use the `proxmox.nodes.get()` notation anyway.

The README should be updated if the `proxmox.get(string)` format is no longer supported.

Using latest version, 1.1.1

**Comment by jhollowe** [comment]
Yeah, it looks like `proxmox.something.get()` and `proxmox.get("something")` return different things due to one being a `ProxmoxResource` object and one being a `ProxmoxAPI` object.

I think making `ProxmoxAPI` inherit from `ProxmoxResource` rather than `ProxmoxResourceBase` might fix this issue, but I'll need to test that theory and see if that actually works.

**Comment by jhollowe** [comment]
If you don't need the entire path to be on the string, you can use the following:

```python
for node in proxmox.nodes.get():
  for virtman in proxmox.nodes.get(f"{node['node']}/qemu"):
    vms.append(virtman["vmid"])
  for cont in proxmox.nodes.get(f"{node['node']}/lxc"):
    containers.append(cont["vmid"])
```
