### ISSUE TITLE
Maintainers welcome

### ISSUE THREAD

**Issue by morph027** [proxmoxer/proxmoxer#5]
As the upstream repo https://github.com/swayf/proxmoxer/ already got abandoned leaving multiple pull requests open, i've came up with the proxmoxer organization to take care. To prevent the same happen to this repo, i'd like to invite more maintainers to this wonderful project, just drop me a message, mail, or an issue comment here.

**Comment by tomjones1977** [comment]
I'd be interested in helping.

**Comment by morph027** [comment]
Sure, go ahead ;)

**Comment by jhollowe** [comment]
yeah, feel free to make PRs for any GitHub issues or any bugs you find.

**Comment by jhollowe** [comment]
I feel like we have a fairly strong group of maintainers right now. We definitely won't dismiss any new people, but I think we don't need this active anymore.

I'm closing for now; we can reopen or discuss in the future if we need to.
