### ISSUE TITLE
is there anyway to whit 1 method ,  start or stop lxc and qemu?

### ISSUE THREAD

**Issue by acairon** [proxmoxer/proxmoxer#52]
Hello i have this 2 methods 

proxmox.nodes(env("PROX_NODE")).lxc(vmid).status.post(action)

and 

proxmox.nodes(env("PROX_NODE")).qemu(vmid).status.post(action)

is there anyway i can do 2 methods in one?  

like 

def method(vmid,type)

proxmox.nodes(env("PROX_NODE")).$type(vmid).status.post(action)

or somethin

**Comment by morph027** [comment]
Nothing to do with proxmoxer in special, but you can do smthg. like

```
def pve_action(type, action):
    methods = {
        "lxc": proxmox.nodes(env("PROX_NODE")).lxc,
        "qemu": proxmox.nodes(env("PROX_NODE")).qemu
    }
    return methods.get(type)

pve_action(type, action).status.post(action)
```

**Comment by acairon** [comment]
sorry if it's a stupid question, as a student I'm learning little by little xD :/

**Comment by morph027** [comment]
No problem, you're welcome! There are no dump questions ;)
