### ISSUE TITLE
what its the best option to display realtime cpu ussage in django? 

### ISSUE THREAD

**Issue by acairon** [proxmoxer/proxmoxer#53]
Good I wanted to know if someone already implemented in django or python some way to obtain the use of the cpu in real time, I have been several days and I can not find the solution I am able to obtain the data and but not show them later

**Comment by jhollowe** [comment]
To get the overall usage, have a look at the [rrddata endpoint](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/rrddata). for the CPU usage of a certain VM or container, look at the rrddata endpoint for [VMs](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/rrddata) and [containers](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc/{vmid}/rrddata).

You can look at how the GUI uses this data or even use the [rdd endpoint](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/rrd) to get a PNG graph of the usage
