### ISSUE TITLE
PyPI package 

### ISSUE THREAD

**Issue by jpastuszuk** [proxmoxer/proxmoxer#6]
As we can clearly see, the upstream of this fork is no longer maintained. 
Hovewer, there is still not PyPI package of this repo on pypi.org for easy incorporation of new PRs.

I would suggest:
1) Clearly stating in this repo, that the upstrem is obsolete
2) Introducing new package to pypi.org and, same stating there, that upstream is deprecated and should not be used.

**Comment by morph027** [comment]
Jip, planned this already. If you or someone wants to help, just let me know and i add you to the org.

**Comment by morph027** [comment]
Great news, @jhollowe contacted me and i've added him to the org. @swayf gave him access to pypi, so we could release new updates.

**Comment by elurex** [comment]
what is the difference between 1.0.3 and 1.0.4?
