### ISSUE TITLE
need help for vm clone

### ISSUE THREAD

**Issue by badsmoke** [proxmoxer/proxmoxer#60]
hello people,

I am currently trying to clone vms using python.
I always have a standard template from which new vms are cloned.

my code looks like this

```
def create_vm(message,proxmox):
    node_name = "server1"
    source_id= 111
    target_id = get_next_id(proxmox)
    vm_name= test
    node = proxmox.nodes(node_name)
    node.qemu.source_id.clone.post(name=vm_name,
        full=1,
        newid=target_id
        )
```
`proxmoxer.core.ResourceException: 400 Bad Request: Parameter verification failed. - b'{"errors":{"vmid":"type check (\'integer\') failed - got \'source_id\'"},"data":null}'`

with a variable in the path unfortunately does not work, but vmid as parameter does not work either

```
node.qemu.clone.post(vmid=source_id, name=vm_name ......
```

`proxmoxer.core.ResourceException: 501 Not Implemented: Method 'POST /nodes/kronos/qemu/clone' not implemented - b'{"data":null}'`

proxmox docu
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/clone

thanks for the help

**Comment by jhollowe** [comment]
try `node.qemu(source_id).clone.post(...)`. This follows a similar syntax as the `node = proxmox.nodes(node_name)` line, putting the given argument in as the next segment of the path for the API call.
You could also do `node(f"qemu/{source_id}/clone").post(...)` if you wanted to use the string path functionality.

**Comment by badsmoke** [comment]
thank you, works great
