### ISSUE TITLE
proxmoxer agent exec-status

### ISSUE THREAD

**Issue by enimath** [proxmoxer/proxmoxer#61]
Hello,

I am trying to check agent exec-status command but proxmoxer don't know anything after "-" so perhaps there is some other keyword to use ?

when I am trying to check on console with pvesh it is working
"pvesh get /nodes/local-11/qemu/10001/agent/exec-status --pid 1017"

my code:
targetnode=local-11
vmid=10001
pid=1017
proxmox.nodes(targetnode).qemu(vmid).agent.exec-status(pid=pid).get()

**Comment by jhollowe** [comment]
This is a limitation of python when using the dotted form. If you change it to the following, it should work (I currently don't have access to my testing rig so I can't test for sure).

```python
proxmox.nodes(targetnode).qemu(vmid).agent("exec-status").get(pid=pid)
```
