### ISSUE TITLE
Add support for local

### ISSUE THREAD

**Issue by McTwist** [proxmoxer/proxmoxer#76]
Currently you are required to access a node "remotely" through its name. But if for some reason you want to run locally and do not want to use any type of authentication, this falls flat.

I would recommend to add a service for local, where it will do exactly like ssh, but using `Popen` instead for local access.

**Comment by jhollowe** [comment]
you can use one of the SSH backends and use "localhost" as the host if you are running Proxmoxer on a PVE/PMG/PBS node.

**Comment by reitermarkus** [comment]
Could a dedicated `local` backend be added? In my case at least, `ssh root@localhost` gets stuck since `localhost` is not in `known_hosts`, and I also don't think it should be.

**Comment by McTwist** [comment]
#77 has already been declined, but please do voice your opinion about this to increase the need for it.

**Comment by reitermarkus** [comment]
This would be very beneficial for use in the Proxmox Ansible module which uses this library. Ansible already ssh's to a given node itself, so this would alleviate the need for depending on another SSH library.

**Comment by jhollowe** [comment]
Ah, yeah that makes sense. I was wondering the utility of local/cli access, but when using Ansible you are already SSHed into the host and running in Python. A single dependency on proxmoxer vs proxmoxer+(openssh|paramiko) is obviously preferred in this setup as well. And the fact that all you need is the SSH access for Ansible and wouldn't need any other creds once connected.

There are some other features I would like to get implemented and released first, but I would be willing to add a local backend in the following release. And yes, there needs to be some refactoring done to reduce duplicate code between SSH and local, but that should be easy.

**Comment by jhollowe** [comment]
Backend name ideas?

👍 for `local`
🚀 for `cli`
comment below for other ideas

**Comment by McTwist** [comment]
Will #77 be used, or will you create your own?
