### ISSUE TITLE
Please support a recent version of requests

### ISSUE THREAD

**Issue by valholl** [proxmoxer/proxmoxer#78]
I see in test_requirements.txt a dependency on `requests < 2.9`, which has been released in 2015.

From what I understand, this is just a problem with tests (specifically with `tests.https_tests.test_pbs_https_connection`), and proxmoxer runs correctly with more recent versions of requests, right?

However, it would be nice if that dependency could be changed to a version of requests from this decade.

Thanks

**Comment by jhollowe** [comment]
Yeah, considering that `nosetest` doesn't work on python 3.10, we will need to completely revamp the whole test tooling. You can use any version of requests, but for the tests to properly function `< 2.9` is needed.

**Comment by jhollowe** [comment]
Work is in progress to update to pytest for version 2.0 which should allow requests to have a floating version (not specifically locked to a specific version).
