### ISSUE TITLE
token expiration (http backend)

### ISSUE THREAD

**Issue by compilenix** [proxmoxer/proxmoxer#9]
I'm writing a tool which may run for several hours. It seems that the api access token times out at some point.

Do you think proxmoxer should detect that and try to aquire a new api access token by itself?

This would require that proxmoxer would need to keep username and password in memory permanently, while the instance of proxmoxer exists.

**Comment by elurex** [comment]
this is a much needed feature or otherwise the process need to be killed and started like every 2 hours or so which cause chaos when there are process are actually calling api gets killed as well

**Comment by compilenix** [comment]
I've already implemented this in an internal fork and is working well for me.

I'll create a PR for this soon.

**Comment by compilenix** [comment]
PR has been created: #12

**Comment by jhollowe** [comment]
@compilenix @elurex Are your scripts consistently using the connection (at least once every 2 hours) or are they sitting idle most of the time?

**Comment by compilenix** [comment]
My script is using the connection between 1 - 8 times a day, Idle time between requests can range from 1 to 24 hours.

Regarding #16: While i like the aproach of recreating the access token without the password, this would currently not resolve the original issue i had.

Suppose you have a service running which only performs requests to the proxmox api couple times a day, the access token / cookie would expire between two api calls and the service would need to recreate the proxmoxer object instance or restarting the whole service.

Two further ideas i have to add:
1. Maybe we could save the password only if the caller explicitly requests it, and do no save it by default.
2. We could spawn a worker thread that renews the access token independent of the caller.

**Comment by jhollowe** [comment]
Yeah, I like the prospects of the first idea. I'll add that to #16 in a bit.

**Comment by jhollowe** [comment]
@compilenix can you try out the PR for a few days with the long_running flag and see if it works for your use case?

**Comment by compilenix** [comment]
I'm really busy lately, i'm trying to test this by next week :)

**Comment by jhollowe** [comment]
would using the api tokens (#10) fill the need for this? It seems like that would be better than storing the password and is designed to have better access control.

**Comment by compilenix** [comment]
It seems like it, if api tokens are working as i think they will be this issue, #12 and #16 would be obsolete and could be closed.
